---
services:
  ansible:
    hostname: ansible
    #build:
    #context: ./ubuntu-ssh
    #dockerfile: Dockerfile
    image: ftutorialsnaen
    container_name: ansible
    ports:
      - "2222:22"
      - "80:80"
    volumes:
      - ./projet:/root/projet
      - ./data/ansible_ssh:/root/.ssh
    networks:
      - ansible_net

  client1:
    privileged: true
    hostname: client1
    build:
      context: ./ubuntu-ssh
      dockerfile: Dockerfile
    container_name: client1
    ports:
      - "2223:22"
      - "3003:3000"
      - "8083:80"
    networks:
      - ansible_net
    volumes:
      - ./data/client1_ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock

  client2:
    privileged: true
    hostname: client2
    build:
      context: ./ubuntu-ssh
      dockerfile: Dockerfile
    container_name: client2
    ports:
      - "2224:22"
      - "3004:3000"
      - "8084:80"
    networks:
      - ansible_net
    volumes:
      - ./data/client2_ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock

  client3:
    privileged: true
    hostname: client3
    build:
      context: ./rocky-ssh
      dockerfile: Dockerfile
    container_name: client3
    ports:
      - "2225:22"
      - "3005:3000"
      - "8085:80"
    networks:
      - ansible_net
    volumes:
      - ./data/client3_ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock

  client4:
    privileged: true
    hostname: client4
    build:
      context: ./rocky-ssh
      dockerfile: Dockerfile
    container_name: client4
    ports:
      - "2226:22"
      - "3006:3000"
      - "8086:80"
    networks:
      - ansible_net
    volumes:
      - ./data/client4_ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock

  quiz-ansible:
    platform: linux/amd64
    image: ftutorials/quiz:ansible-4
    container_name: quiz-ansible
    ports:
      - "3000:3000"
    networks:
      - ansible_net

networks:
  ansible_net:
    driver: bridge
